### ISSUE TITLE
error: failed to download `libc v0.2.70`   in windows

### ISSUE THREAD

**Issue by IThawk** [rust-lang/libc#1761] opened 2020-05-14 22:18 UTC
F:\workspace\language\rust\examples>cargo build
error: failed to download `libc v0.2.70`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.70\Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  unexpected character found: `\u{0}` at line 1 column 1

F:\workspace\language\rust\examples>

**Comment by JohnTitor** [comment] 2020-05-14 23:16
I cannot reproduce this issue on my local, I guess you should clean-up your current deps by `cargo clean` or similar way.

**Comment by JohnTitor** [comment] 2020-05-21 06:39
Closing as it should be a user-side issue. Feel free to re-comment here if there're any updates.

**Closed by JohnTitor** 2020-05-21 06:39 UTC
