### ISSUE TITLE
libc should let you manage errno

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/libc#47] opened 2015-11-07 06:57 UTC
Originally filed as https://github.com/rust-lang/rust/issues/17714

**Comment by kamalmarhubi** [comment] 2016-01-25 19:37
There's also some discussion at https://github.com/rust-lang/rust/pull/18642

**Comment by nodakai** [comment] 2016-04-03 14:40
+1 for `fn errno() -> c_int` and `fn set_errno(c_int)`. We already have a fundamental semantic gap between Rust and C here, so there's no point in sticking to literally the same identifiers with the C language spec.

I believe there are several C APIs for which checking `errno` is the best way to detect their errors, so clearing `errno` beforehand can be an essential requirement. For example... well... `strtol(3)` with `base!=10`?

**Comment by kamalmarhubi** [comment] 2016-04-03 15:39
I'd like us to fix this too. Another use case is writing libraries in Rust that expose a C ABI interface using `errno` for error signalling.

**Comment by kamalmarhubi** [comment] 2016-04-03 15:47
In nix, we have an [`errno` module](https://github.com/nix-rust/nix/blob/master/src/errno.rs) that provides `errno() -> i32` across unix platforms. We don't have a `set_errno()` function though.

**Comment by alexcrichton** [comment] 2016-04-03 17:46
This library's scope is now [defined by an RFC](https://github.com/rust-lang/rfcs/blob/master/text/1291-promote-libc.md) so if these sorts of function as such exist in libc on various platforms then we can certainly bind them, otherwise it'll be up to an external crate to add extra "rustic handling" for these functions.

Currently we don't necessarily keep an issue for all APIs we'd like to implement, so I'm going to close this, but PRs are always welcome!

**Closed by alexcrichton** 2016-04-03 17:46 UTC

**Comment by nodakai** [comment] 2016-04-03 18:50
@alexcrichton 

>  if these sorts of function as such exist in libc on various platforms then we can certainly bind them,

I assume you didn't mean a "C function" for which `libc.so` has a symbol here, because the RFC 
includes "C macros" such as [`CPU_ZERO()`](https://github.com/rust-lang/libc/blob/f288e185f491bbbe01085f3756b2fd47b439bb84/src/unix/notbsd/linux/mod.rs#L377) in its target.

[POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/functions/errno.html) states

> The value of errno shall be defined only after a call to a function for which it is explicitly stated to be set and until it is changed by the next function call or **if the application assigns it a value**.

(emphasis mine.)

So assignment to the lvalue `errno` *is* a part of the public interface of what you call `libc`. Given that C's notion of "lvalue" doesn't readily map to Rust's (especially when we consider memory safety and multithreading,) and `errno` is *typically* implemented as a C macro, it would best fit with the spirit of the RFC to provide a setter function `fn set_errno()`.

So the topic is not about "rustic handling." It's about whether you can handle it or not with the libc crate.

And again, because the original C interface based on a "lvalue" doesn't readily map to Rust, it is definitely worth having a discussion on the interface here. You shouldn't simply close this ticket.

I'd even say it is `__errno_location()` which should be removed from the libc crate because it is merely an implementation detail. The glibc reference doesn't even spend a word on it.

Do you think it makes more sense to define a Rust macro which closely mimics the typical `errno` macro (in C)? I don't think so.

```rust
extern {
    fn malloc(n: usize) -> *mut i8;  // just for an experiment
    pub fn __errno_location() -> *mut i32;  // implementation detail, but it has to be pub
}

macro_rules! errno {
    () => (
        *__errno_location()
    )
}

fn main() {
    println!("{:?}", unsafe { malloc(1 << 63) });  // sets errno
    println!("{}", unsafe { errno!() });
    unsafe { errno!() = 0 };
    println!("{}", unsafe { errno!() });
}
```

**Comment by sorear** [comment] 2016-04-03 21:09
Strongly agree that any library whose scope includes access to standard C library functions should include a way to set `errno` to 0.  Both [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/functions/errno.html#tag_16_110_07):

> An application that needs to examine the value of errno to determine the error should set it to 0 before a function call, then inspect it before a subsequent function call.

and [C99](http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf):

> Thus, a program that uses errno for error checking should set it to zero before a library function call, then inspect it before a subsequent library function call. Of course, a library function can save the value of errno on entry and then set it to zero, as long as the original value is restored if errno’s
value is still zero just before the return. (§7.5, footnote 176)

don't merely permit modifying errno, they specify that applications and user-created libraried *should* do it under certain situations.  Furthermore, neither of them permits referencing `__errno_location` (declaring an identifier with two leading underscores is undefined behavior).

In every implementation I know of, `&errno` is legal, but this does not seem to be guaranteed by either C or POSIX (I can't find anything that would forbid `struct __thread_state { ...; signed int __errno: 14; ... }; extern struct __thread_state *__current_thread(); #define errno (__current_thread()->__errno)`).  `errno = 0;` and `errno = ENOENT;` are legal by spec though.

So, given that the scope of libc in RFC1291 includes "C macros" and "C statics", and errno is usually one or the other of those, and the specified interface to errno allows and in some cases *requires* assigning to errno, I would argue that our binding to errno is objectively incomplete and this is a needed improvement.

**Comment by bluss** [comment] 2016-04-03 22:23
Can crate libc even implement setting errno properly without compiling a C shim for it? Without shim it requires all the platforms to provide something like `__errno_location`. If a shim is needed, it makes sense to use a separate crate to provide it.

**Comment by sorear** [comment] 2016-04-03 22:54
@bluss 

1. You could make exactly the same argument about get_errno.  Are you willing to state that Rust code using the libc crate should have no access of any kind to errno?
2. AFAICT, all Rust-supported POSIXy platforms do provide something like `__errno_location`; glibc and musl call it that, Android/bionic has [`__errno`](https://github.com/android/platform_bionic/blob/master/libc/include/errno.h#L47) (not bound by the libc crate?), FreeBSD has [`__error`](https://doc.rust-lang.org/libc/x86_64-unknown-freebsd/libc/fn.__error.html), OpenBSD has [`__errno`](https://doc.rust-lang.org/libc/x86_64-unknown-openbsd/libc/fn.__errno.html).  VS CRT documents a [`_errno`](https://msdn.microsoft.com/en-us/library/t3ayayh1.aspx).
3. My interpretation of RFC1291 is that a Rust program using the libc crate should be approximately as portable as the corresponding C program.  So we shouldn't do anything about the fact that different platforms have different Exxx constants, but we should provide read and write access to the `errno` variable, because C programs can use `errno` without knowing how it is #defined.

**Comment by bluss** [comment] 2016-04-03 23:01
1. I said the opposite in issue #81

**Comment by kamalmarhubi** [comment] 2016-04-04 14:25
Since the issue is that libc scope as defined in RFC 1291 doesn't include anything about `errno`, I opened https://github.com/rust-lang/rfcs/pull/1571 to add it. Let's see where that goes.

**Comment by alexcrichton** [comment] 2016-04-04 16:12
Thanks @kamalmarhubi! I think that's the best next step here.

**Comment by pickfire** [comment] 2020-05-07 10:12
is this still valid or can we move https://github.com/lambda-fairy/rust-errno here?
