### ISSUE TITLE
Build appears broken on FreeBSD

### ISSUE THREAD

**Issue by inferiorhumanorgans** [rust-lang/libc#1192] opened 2019-01-02 03:00 UTC
```
$ uname -a
FreeBSD devbox 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64
$ git rev-parse HEAD
7b3d2c6fa739614625a73f296f534f63d2fdf4d4
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ rustc --version
rustc 1.33.0-nightly (9eac38634 2018-12-31)
$ cargo test
   Compiling libc-test v0.1.0 (/usr/home/user/rust-libc/libc-test)
error: failed to run custom build command for `libc-test v0.1.0 (/usr/home/user/rust-libc/libc-test)`
process didn't exit successfully: `/usr/home/user/rust-libc/target/debug/build/libc-test-1498f226eb0e039a/build-script-build` (exit code: 101)
--- stdout
-----------------------------------------
cargo:rerun-if-changed=../src/lib.rs
cargo:rerun-if-changed=../src/macros.rs
cargo:rerun-if-changed=../src/dox.rs
cargo:rerun-if-changed=../src/unix/mod.rs
cargo:rerun-if-changed=../src/unix/bsd/mod.rs
cargo:rerun-if-changed=../src/unix/bsd/freebsdlike/mod.rs
cargo:rerun-if-changed=../src/unix/bsd/freebsdlike/freebsd/mod.rs
cargo:rerun-if-changed=../src/unix/bsd/freebsdlike/freebsd/x86_64.rs
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-freebsd")
CC_x86_64-unknown-freebsd = None
CC_x86_64_unknown_freebsd = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-freebsd = None
CFLAGS_x86_64_unknown_freebsd = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-Wno-address-of-packed-member" "-Wno-deprecated-declarations" "-Wno-deprecated-declarations" "-D_WITH_GETLINE" "-o" "/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.o" "-c" "/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c"
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:12633:28: error: incompatible pointer types returning 'ino_t *' (aka 'unsigned long *') from a function with result type 'uint32_t *' (aka 'unsigned int *') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                    return &b->d_fileno;
cargo:warning=                           ^~~~~~~~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:12675:28: error: incompatible pointer types returning '__uint16_t *' (aka 'unsigned short *') from a function with result type 'uint8_t *' (aka 'unsigned char *') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                    return &b->d_namlen;
cargo:warning=                           ^~~~~~~~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:13334:28: error: incompatible pointer types returning 'char (*)[1024]' from a function with result type 'char (*)[88]' [-Werror,-Wincompatible-pointer-types]
cargo:warning=                    return &b->f_mntfromname;
cargo:warning=                           ^~~~~~~~~~~~~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:13348:28: error: incompatible pointer types returning 'char (*)[1024]' from a function with result type 'char (*)[88]' [-Werror,-Wincompatible-pointer-types]
cargo:warning=                    return &b->f_mntonname;
cargo:warning=                           ^~~~~~~~~~~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:13658:28: error: returning 'shmatt_t *' (aka 'unsigned int *') from a function with result type 'int *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
cargo:warning=                    return &b->shm_nattch;
cargo:warning=                           ^~~~~~~~~~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:17192:24: error: incompatible pointer types returning 'int (void *, size_t, int)' (aka 'int (void *, unsigned long, int)') from a function with result type 'int (*)(const void *, size_t, int)' (aka 'int (*)(const void *, unsigned long, int)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return mprotect;
cargo:warning=                       ^~~~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:17332:24: error: incompatible pointer types returning 'void (locale_t)' (aka 'void (struct _xlocale *)') from a function with result type 'int (*)(locale_t)' (aka 'int (*)(struct _xlocale *)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return freelocale;
cargo:warning=                       ^~~~~~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:17377:24: error: incompatible pointer types returning 'ssize_t (int, void *, size_t, long, int)' (aka 'long (int, void *, unsigned long, long, int)') from a function with result type 'int (*)(int, void *, size_t, long, int)' (aka 'int (*)(int, void *, unsigned long, long, int)') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                return msgrcv;
cargo:warning=                       ^~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:17829:28: error: incompatible pointer types returning '__uint64_t *' (aka 'unsigned long *') from a function with result type 'uint32_t *' (aka 'unsigned int *') [-Werror,-Wincompatible-pointer-types]
cargo:warning=                    return &b->st_gen;
cargo:warning=                           ^~~~~~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:17834:28: error: no member named 'st_lspare' in 'stat'
cargo:warning=                    return offsetof(struct stat, st_lspare);
cargo:warning=                           ^                     ~~~~~~~~~
cargo:warning=/usr/include/stddef.h:75:31: note: expanded from macro 'offsetof'
cargo:warning=#define offsetof(type, field)   __offsetof(type, field)
cargo:warning=                                ^                ~~~~~
cargo:warning=/usr/include/sys/cdefs.h:476:34: note: expanded from macro '__offsetof'
cargo:warning=#define __offsetof(type, field)  __builtin_offsetof(type, field)
cargo:warning=                                 ^                        ~~~~~
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:17838:40: error: no member named 'st_lspare' in 'struct stat'; did you mean 'st_spare'?
cargo:warning=                    return sizeof(foo->st_lspare);
cargo:warning=                                       ^~~~~~~~~
cargo:warning=                                       st_spare
cargo:warning=/usr/include/sys/stat.h:191:13: note: 'st_spare' declared here
cargo:warning=        __uint64_t st_spare[10];
cargo:warning=                   ^
cargo:warning=/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c:17843:32: error: no member named 'st_lspare' in 'struct stat'; did you mean 'st_spare'?
cargo:warning=                    return &b->st_lspare;
cargo:warning=                               ^~~~~~~~~
cargo:warning=                               st_spare
cargo:warning=/usr/include/sys/stat.h:191:13: note: 'st_spare' declared here
cargo:warning=        __uint64_t st_spare[10];
cargo:warning=                   ^
cargo:warning=12 errors generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-Wall" "-Wextra" "-Werror" "-Wno-unused-parameter" "-Wno-type-limits" "-Wno-address-of-packed-member" "-Wno-deprecated-declarations" "-Wno-deprecated-declarations" "-D_WITH_GETLINE" "-o" "/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.o" "-c" "/usr/home/user/rust-libc/target/debug/build/libc-test-b121af1b77517199/out/main.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I get similar output with the current stable toolchain (`rustc 1.31.1 (b6c32da9b 2018-12-18)`).  However the CI box (on FreeBSD 11) appears to be working.

https://cirrus-ci.com/build/5197130937401344

**Comment by inferiorhumanorgans** [comment] 2019-01-02 17:39
It looks like Cirrus has a FreeBSD 12 VM as well.  Considering that 12 is now the new stable branch, it might be worth including a 12 VM alongside the 11 one.

**Comment by asomers** [comment] 2019-01-02 18:02
This is caused by #570 .  FreeBSD 12 increased the size of `ino_t` from 32 to 64 bits, and made a number of other changes as well.  Unfortunately, Rust's decision to use FFI for C interoperability makes it very hard to deal with C API changes, even changes that native C code can handle seamlessly.

Even though the tests don't pass, libc works on FreeBSD 12.  For changed functions, libc will bind to the FreeBSD 11 compat version.  That's not an ideal solution, but it will work until #570 is fixed.

**Comment by inferiorhumanorgans** [comment] 2019-01-03 07:10
FWIW I'm working on setting up a more comprehensive test rig locally.  Currently I've got some jails for FreeBSD 10, 11, and 12 hooked into buildbot.  Longer-term I'm going to hook up some DF/Open/NetBSD VMs as well.  I don't really have the resources to keep them running 24x7, but I'd be happy to run them periodically (weekly? monthly?) as something like libc runs through the tests pretty quickly.

**Comment by asomers** [comment] 2019-01-04 18:13
Could a maintainer please close this bug as a duplicate of #570 ?

**Closed** 2019-01-04 18:19 UTC
Labels: bug-outdated-type
