### ISSUE TITLE
Seeming problem with the freebsd version on freebsd 14.2

### ISSUE THREAD

**Issue by Owl-Lord** [rust-lang/libc#4175] opened 2024-12-06 21:10 UTC
problem discription:
 in trying to compile a project using this project for freebsd a type error arises with its origins in this crate
                                     that type error steming from the type alias dev_t in the newest version of this crate.
                                     the code expected u64 and got u32.
                                     im not that caught up on kernel api's but afaik this should not be as freebsd is a 64 bit os.
                                     i might be barking up the wrong tree here

more context:
 i am trying to port the cosmic desktop enviroment to the freebsd operating system.
                          i have however encountered a type error which i managed to to track down to this library
                          i however dont know if this is intended or not.

**Comment by tgross35** [comment] 2024-12-07 04:08
What version of this crate is in your lockfile? And can you post the full error with context?

Cc @asomers

**Comment by Owl-Lord** [comment] 2024-12-07 11:54
i tracked the version down to 0.2.153

the following is the output of cargo build on the newest version of the cosmic-edit application which uses this library through dependencys:
```rust    Compiling iced_wgpu v0.14.0-dev (https://github.com/pop-os/libcosmic.git#b524ccb0)
   Compiling encoding_rs_io v0.1.7
   Compiling mime_guess v2.0.5
   Compiling rust-ini v0.20.0
   Compiling darling v0.20.10
   Compiling zstd-safe v7.2.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling fluent v0.16.1
   Compiling iced_winit v0.14.0-dev (https://github.com/pop-os/libcosmic.git#b524ccb0)
   Compiling parking_lot v0.12.3
   Compiling rust-embed v8.5.0
   Compiling csscolorparser v0.6.2
   Compiling hmac v0.12.1
   Compiling zeroize_derive v1.4.2
   Compiling thiserror-impl v2.0.4
   Compiling avif-serialize v0.8.2
   Compiling dirs-sys-next v0.1.2
   Compiling is-docker v0.2.0
   Compiling humantime v2.1.0
   Compiling lockfree-object-pool v0.1.6
   Compiling anstyle v1.0.10
   Compiling zip v2.2.1
   Compiling byteorder-lite v0.1.0
   Compiling is_terminal_polyfill v1.70.1
   Compiling almost v0.2.0
   Compiling hashbrown v0.14.5
   Compiling zune-core v0.4.12
   Compiling colorchoice v1.0.3
   Compiling bumpalo v3.16.0
   Compiling grid v0.11.0
   Compiling anstyle-query v1.1.2
   Compiling zeroize v1.8.1
   Compiling anstream v0.6.18
   Compiling cosmic-theme v0.1.0 (https://github.com/pop-os/libcosmic.git#b524ccb0)
   Compiling proc-macro-error v1.0.4
   Compiling taffy v0.3.11 (https://github.com/DioxusLabs/taffy?rev=7781c70#7781c702)
   Compiling image-webp v0.2.0
   Compiling zune-jpeg v0.4.13
   Compiling zopfli v0.8.1
   Compiling ravif v0.11.11
   Compiling dirs-next v2.0.0
   Compiling is-wsl v0.4.0
error[E0308]: mismatched types
   --> /home/luca/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/wgpu/src/window/x11.rs:148:68
    |
148 | ...                   return super::ids_from_dev(dev);
    |                              ------------------- ^^^ expected `u64`, found `u32`
    |                              |
    |                              arguments to this function are incorrect
    |
note: function defined here
   --> /home/luca/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/wgpu/src/window.rs:17:4
    |
17  | fn ids_from_dev(dev: u64) -> Option<(u16, u16)> {
    |    ^^^^^^^^^^^^ --------
help: you can convert a `u32` to a `u64`
    |
148 |                                         return super::ids_from_dev(dev.into());
    |                                                                       +++++++

error[E0308]: mismatched types
   --> /home/luca/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/wgpu/src/window/x11.rs:169:29
    |
169 |         super::ids_from_dev(dev)
    |         ------------------- ^^^ expected `u64`, found `u32`
    |         |
    |         arguments to this function are incorrect
    |
note: function defined here
   --> /home/luca/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/wgpu/src/window.rs:17:4
    |
17  | fn ids_from_dev(dev: u64) -> Option<(u16, u16)> {
    |    ^^^^^^^^^^^^ --------
help: you can convert a `u32` to a `u64`
    |
169 |         super::ids_from_dev(dev.into())
    |                                +++++++

error[E0308]: mismatched types
  --> /home/luca/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/wgpu/src/window.rs:20:15
   |
20 |         major(dev),
   |         ----- ^^^ expected `u32`, found `u64`
   |         |
   |         arguments to this function are incorrect
   |
note: function defined here
  --> /home/luca/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.41/src/fs/makedev.rs:33:8
   |
33 | pub fn major(dev: Dev) -> u32 {
   |        ^^^^^
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
   |
20 |         major(dev.try_into().unwrap()),
   |                  ++++++++++++++++++++

   Compiling freedesktop-icons v0.2.6
error[E0308]: mismatched types
  --> /home/luca/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/wgpu/src/window.rs:21:15
   |
21 |         minor(dev)
   |         ----- ^^^ expected `u32`, found `u64`
   |         |
   |         arguments to this function are incorrect
   |
note: function defined here
  --> /home/luca/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.41/src/fs/makedev.rs:22:8
   |
22 | pub fn minor(dev: Dev) -> u32 {
   |        ^^^^^
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
   |
21 |         minor(dev.try_into().unwrap())
   |                  ++++++++++++++++++++

   Compiling i18n-embed v0.14.1
   Compiling dashmap v5.5.3
   Compiling thiserror v2.0.4
For more information about this error, try `rustc --explain E0308`.
   Compiling zstd v0.13.2
error: could not compile `iced_wgpu` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by asomers** [comment] 2024-12-07 14:17
This is not a bug in libc, this is a bug in libcosmic.  And it is _exactly_ the type of portability bug that arises in applications which are written for one operating system and never tested on another.  libc's definition is correct*.

* Note that the definition of `dev_t` actually changed in FreeBSD 12, but libc uses the FreeBSD 11 compatibility layer, which is why it still defines `dev_t` as 32-bit.  But that's a long story...

**Comment by Owl-Lord** [comment] 2024-12-07 14:38
so what would a fix be?

**Comment by asomers** [comment] 2024-12-07 14:52
> so what would a fix be?

You have to fix libcosmic, not libc. If you need help with that, I suggest you ask the libcosmic maintainers, not us.

**Comment by Owl-Lord** [comment] 2024-12-07 15:06
i shall do so!
i just was thinking it might be libc as i dont know that much about the clibs of unix systems

**Comment by tgross35** [comment] 2024-12-07 22:31
Thanks Alan, I don't think there is anything to do here so I'll close this.

**Closed by tgross35** 2024-12-07 22:31 UTC
Labels: C-bug, O-bsd
