### ISSUE TITLE
`isatty` gives different results depending on wheter `cargo run` is used

### ISSUE THREAD

**Issue by saghm** [rust-lang/libc#239] opened 2016-03-26 01:32 UTC
Depending on whether a binary is run directly or with `cargo run`, `isatty()` seems to give different results. For example, given the following code:

```rust
fn main() {
    let fileno = unsafe { libc::STDIN_FILENO as i32 };
    let isatty = unsafe { libc::isatty(fileno) };
    println!("fileno: {}, isatty: {}", fileno, isatty);
}
```

When run with `cargo run`, the output is

```
fileno: 0, isatty: 0
```

However, when the binary is directly run, the output is

```
fileno: 0, isatty: 0
```

I'm not sure if this is expected or not, or if it's fixable from Rust rather than from the C implementation, but I thought I was worth checking just in case.

EDIT: I'm realizing this is more like caused by something in Cargo than libc, so there's probably nothing that can be done from here.

**Comment by posborne** [comment] 2016-03-26 03:23
The output appears to be the same in the sample you provided?  Did you paste the wrong output for one of the two?

**Comment by saghm** [comment] 2016-03-26 03:38
Sorry, forgot to mention this only happens on the latest nightly (2016-03-24), not any earlier nightlies or on stable.

**Comment by alexcrichton** [comment] 2016-03-26 05:16
I believe this is a dupe of https://github.com/rust-lang/rust/issues/32254 caused by https://github.com/rust-lang/rust/pull/31618 and fixed in https://github.com/rust-lang/rust/pull/32257, so closing in favor of https://github.com/rust-lang/rust/issues/32254 but thanks for the report!

**Closed by alexcrichton** 2016-03-26 05:16 UTC
